### ISSUE TITLE
Composing Components Type Error "... is not assignable to parameter of type 'string'"

### ISSUE THREAD

**Issue by zwagnr** [macaron-css/macaron#15] opened 2022-12-16 00:11 UTC
In Stiches you can compose components from other elements, i.e.  where _MyCoolElement_ is another component.

Currently in Macaron it will throw a type error "... is not assignable to parameter of  type 'string'"

The functionality still works and I have just been using //@ts-expect-error but thats not ideal.

```tsx
const Button = styled(MyCoolElement, {
  base: {
    backgroundColor: 'gainsboro',
  },
});
```

**Comment by Mokshit06** [comment] 2022-12-16 01:52
Hi @zwagnr, thanks for noticing this. Are you using the solid or the react adapter?

**Comment by zwagnr** [comment] 2022-12-16 04:08
React!

**Comment by Mokshit06** [comment] 2022-12-17 12:51
Can you send a minimal reproduction of this? I tried this and it seems to work for me

**Comment by kavinvalli** [comment] 2022-12-17 13:07
> Can you send a minimal reproduction of this? I tried this and it seems to work for me

Seems to be working for me as well

**Comment by zwagnr** [comment] 2022-12-17 13:43
It "works" for me as well, just throws the type error. Is it not giving you a type error?

I'm traveling all weekend so I'll try to send a CodeSandbox as soon as I can!

**Comment by Mokshit06** [comment] 2023-05-21 12:49
I believe this issue is fixed in the new versions, so closing it. Feel free to open them if you face it again!

**Closed by Mokshit06** 2023-05-21 12:49 UTC
